### ISSUE TITLE
Proxy + Neon EVM unstable work

### ISSUE THREAD

**Issue by mich-master** [neonlabsorg/neon-evm#237]
Sometimes the Proxy + Neon EVM bundle works unstably.
One time an operation via Proxy i.e. test execution, contract deployments etc. proceeds well but the other time it fails inside the same environment.

┆Issue is synchronized with this [Jira Task](https://neonlabs.atlassian.net/browse/NEON-174) by [Unito](https://www.unito.io)

**Comment by mich-master** [comment]
For example, today a run OpenZeppelin unit tests. One of them is ERC2771Context contract test

One run it fails and gives the error message:
_Contract: ERC2771Context
       when receiving a relayed call
         msgSender
           returns the relayed transaction original sender:
     Error: Transaction simulation failed: Error processing Instruction 0: invalid account data for instruction_

Another run passes the same way as standard.

**Comment by mich-master** [comment]
Sometimes (not each time) Truffle contract deployment fails. The error message is
_Error:  *** Deployment Failed ***
"ERC20FlashMintMock" -- Transaction simulation failed: Error processing Instruction 0: invalid account data for instruction._

**Comment by mich-master** [comment]
Sometimes (not each time) Truffle contract deployment fails with the error message
_/home/mich/node_modules/web3-core-helpers/lib/errors.js:43
        return new Error(message);
               ^
Error: PollingBlockTracker - encountered an error while attempting to update latest block:
Error: Invalid JSON RPC response: ""_

**Comment by mich-master** [comment]
**Sometimes an error "Invalid JSON RPC response" happens during deployment**
Error: Invalid JSON RPC response: ""
    at Object.InvalidResponse (/home/mich/node_modules/web3-core-helpers/lib/errors.js:43:16)
    at XMLHttpRequest.request.onreadystatechange (/home/mich/node_modules/web3-providers-http/lib/index.js:95:32)
    at XMLHttpRequestEventTarget.dispatchEvent (/home/mich/node_modules/xhr2-cookies/xml-http-request-event-target.ts:44:13)
    at XMLHttpRequest._setReadyState (/home/mich/node_modules/xhr2-cookies/xml-http-request.ts:219:8)
    at XMLHttpRequest._onHttpRequestError (/home/mich/node_modules/xhr2-cookies/xml-http-request.ts:379:8)
    at ClientRequest.<anonymous> (/home/mich/node_modules/xhr2-cookies/xml-http-request.ts:266:37)
    at ClientRequest.emit (events.js:400:28)
    at Socket.socketOnEnd (_http_client.js:499:9)
    at Socket.emit (events.js:412:35)
    at endReadableNT (internal/streams/readable.js:1317:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
Truffle v5.4.9 (core: 5.4.9)
Node v14.17.6
UnhandledRejections detected

**Comment by mich-master** [comment]
**The error "Invalid JSON RPC response" emerges due to the heavy loading of a server on which Proxy and environment runs.**
Truffle (or probably other software) cannot establish a connection to Proxy and results in the error.
