### ISSUE TITLE
Can't deploy the "ERC20Mock.sol" contract from the OpenZeppelin library via Remix

### ISSUE THREAD

**Issue by mich-master** [neonlabsorg/neon-evm#399]
**Impact:**
_General_

**STR:**

1. Try to deploy the "ERC20Mock.sol" contract from the OpenZeppelin library via Remix

**Actual result:**
> creation of ERC20Mock errored: [ethjs-query] while formatting outputs from RPC '{"value":{"code":-32603"data":{"code":-32002"message":"Verifying nonce before send transaction: Error processing Instruction 1: invalid program argument""data":{"logs":["/src/entrypoint.rs Invalid Ethereum transaction nonce: acc 0 trx 1"]}}}}'

**Expected result:**
Contract deployed successfully.

Proxy log:

> 2021-12-02 05:25:43,358 - pid:25 [D] eth_sendRawTransaction:407 - Eth Sender: e3a1b0d74ad7caf365cb37662a2d9c3e8821dc85
2021-12-02 05:25:43,358 - pid:25 [D] eth_sendRawTransaction:408 - Eth Signature: ec3c745c5a01e07357b6e833d3c5f0d003ce8c23cf4403e1c4729052981a38cb0cd498802527e3efeb4726008c878ebbd1daf269493cfaf20c001831c23013dd00
2021-12-02 05:25:43,358 - pid:25 [D] eth_sendRawTransaction:409 - Eth Hash: 0x0460d9e1cebed23fe8fc3b7880d69399f4d4ae7206a606a12d11d4a54667af98
2021-12-02 05:25:43,359 - pid:25 [D] eth_getTransactionCount:282 - eth_getTransactionCount: 0xe3a1b0d74ad7caf365cb37662a2d9c3e8821dc85
2021-12-02 05:25:43,359 - pid:25 [D] call:34 - Calling: neon-cli --commitment=recent --url http://localhost:8899 --evm_loader=53DfF883gyixYNXnM7s5xhdeyV8mVk9T4i2hGV9vG9io create-program-address 0xe3a1b0d74ad7caf365cb37662a2d9c3e8821dc85
2021-12-02 05:25:43,386 - pid:25 [D] eth_sendRawTransaction:413 - Eth Sender trx nonce: 0
2021-12-02 05:25:43,387 - pid:25 [D] eth_sendRawTransaction:414 - Operator nonce: 1
Traceback (most recent call last):
  File "/opt/proxy/plugin/solana_rest_api.py", line 595, in process_request
    response['result'] = method(*params)
  File "/opt/proxy/plugin/solana_rest_api.py", line 417, in eth_sendRawTransaction
    raise EthereumError(-32002, 'Verifying nonce before send transaction: Error processing Instruction 1: invalid program argument'
proxy.plugin.solana_rest_api_tools.EthereumError: (-32002, 'Verifying nonce before send transaction: Error processing Instruction 1: invalid program argument', {'logs': ['/src/entrypoint.rs Invalid Ethereum transaction nonce: acc 0, trx 1']})
2021-12-02 05:25:43,390 - pid:25 [D] handle_request:640 - >>> 139951008974592 0x7f48e26cfbe0 {"jsonrpc": "2.0", "id": 3397266049137, "error": {"code": -32002, "message": "Verifying nonce before send transaction: Error processing Instruction 1: invalid program argument", "data": {"logs": ["/src/entrypoint.rs Invalid Ethereum transaction nonce: acc 0, trx 1"]}}}
'

┆Issue is synchronized with this [Jira Task](https://neonlabs.atlassian.net/browse/NEON-217) by [Unito](https://www.unito.io)

**Comment by mich-master** [comment]
The problem solves by resetting Metamask account. It's specific for Neon EVM by now.
