### ISSUE TITLE
ERROR: relation "constants" does not exist

### ISSUE THREAD

**Issue by AndreyVelde** [neonlabsorg/neon-evm#695]
Hi all. I'm acting here as an operator.
I am running two docker containers following the 
[guide](https://docs.neon-labs.org/docs/operating/operator_guide)

postgresql:

```
docker run --rm -ti --network=host
-e POSTGRES_DB=my_db
-e POSTGRES_USER=my_user
-e POSTGRES_PASSWORD=my_password
--name=postgres postgres:14.0
```

neon-evm proxy:

```
docker run --rm -ti --network=host
-e CONFIG=devnet
-e SOLANA_URL="http://xxx.xxx.xxx.xxx:8899/"
-e POSTGRES_DB=my_db
-e POSTGRES_USER=my_user
-e POSTGRES_PASSWORD=my_password
-v /root/key/identity_keypair.json:/root/.config/solana/id.json neonlabsorg/proxy:v0.8.0
```

RPC-node for solana is on a separate machine. Solana version 1.10.21
I am getting error in neon-evm proxy output

```
2022-06-11 16:16:49.149 E handler.py:413 161 proxy.http.handler:Undefined {} Exception while handling connection <socket.socket fd=61, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('yyy.yyy.yyy.yyy', 9090), raddr=('167.60.9.232', 39143)>
Traceback (most recent call last):
  File "/opt/proxy/http/handler.py", line 397, in run
    self.initialize()
  File "/opt/proxy/http/handler.py", line 138, in initialize
    instance = class(
  File "/opt/proxy/http/server/web.py", line 68, in __init__
    instance = class(
  File "/usr/local/lib/python3.8/dist-packages/logged_groups/logging.py", line 156, in __init__
    orig_init(self, *args, **kws)
  File "/opt/proxy/plugin/neon_rpc_api_plugin.py", line 48, in __init__
    self.model = NeonRpcApiPlugin.getModel()
  File "/opt/proxy/plugin/neon_rpc_api_plugin.py", line 57, in getModel
    modelInstance = NeonRpcApiModel()
  File "/usr/local/lib/python3.8/dist-packages/logged_groups/logging.py", line 156, in __init__
    orig_init(self, *args, **kws)
  File "/opt/proxy/neon_rpc_api_model/neon_rpc_api_model.py", line 52, in __init__
    self._db = MemDB(self._solana)
  File "/usr/local/lib/python3.8/dist-packages/logged_groups/logging.py", line 156, in __init__
    orig_init(self, *args, **kws)
  File "/opt/proxy/memdb/memdb.py", line 18, in __init__
    self._db = IndexerDB(solana)
  File "/usr/local/lib/python3.8/dist-packages/logged_groups/logging.py", line 156, in __init__
    orig_init(self, *args, **kws)
  File "/opt/proxy/indexer/indexer_db.py", line 34, in __init__
    if k not in self._constants:
  File "/opt/proxy/indexer/sql_dict.py", line 55, in __contains__
    cur.execute(f'SELECT 1 FROM {self._table_name} WHERE key = %s', (bin_key,))
psycopg2.errors.UndefinedTable: relation "constants" does not exist
LINE 1: SELECT 1 FROM constants WHERE key = 'min_receipt_slot'
```

and similarly I have in the postrgresql process the output

```
2022-06-11 16:30:34.989 UTC [1332] ERROR: relation "constants" does not exist at character 15
2022-06-11 16:30:34.989 UTC [1332] STATEMENT: SELECT 1 FROM constants WHERE key = 'min_receipt_slot'
```

Is this my mistake or is it just worth waiting for future updates?
I understand maybe I should ask this question in the discord in the operators section, and it was asked, but the error has not been resolved for the second month and there are no answers from the developers.

┆Issue is synchronized with this [Jira Task](https://neonlabs.atlassian.net/browse/NEON-7) by [Unito](https://www.unito.io)

**Comment by AndreyVelde** [comment]
Any news on this issue?
